sudo: false
language: elixir
elixir:
  - 1.3.4
otp_release:
  - 18.3
  - 19.1
script:
  - echo "===> Running with Erlang $TRAVIS_OTP_RELEASE";
    if [ "$TRAVIS_OTP_RELEASE" == "18.3" ]; then
      echo "===> Testing with code coverage";
      MIX_ENV=test mix coveralls.travis;
    else
      echo "===> Testing without code coverage";
      mix test;
    fi
